### ISSUE TITLE
大佬请教下

### ISSUE THREAD

**Issue by enenH** [vrolife/kagent#1]
这个是可以在没有内核源码的情况下编译模块吗

**Comment by vrolife** [comment]
是的,但是只能用有限的api.

**Comment by enenH** [comment]
这个源码是完整的吗，前面获取了一大堆东西，但对ko的修改只看到了 vermagic和name

**Comment by vrolife** [comment]
是完整的.对ko要修改的地方确实也不多.但是如何该改为啥,就需要获取一堆信息.
